# Generated by Django 2.1.5 on 2020-07-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='questionFile',
            new_name='questionFiles',
        ),
        migrations.AddField(
            model_name='question',
            name='testFile',
            field=models.TextField(default=None),
        ),
    ]
