# Generated by Django 2.1.5 on 2020-07-12 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20200712_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionfiles',
            name='question',
        ),
        migrations.RemoveField(
            model_name='file',
            name='questionFiles',
        ),
        migrations.AddField(
            model_name='file',
            name='question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='question.Question'),
        ),
        migrations.DeleteModel(
            name='QuestionFiles',
        ),
    ]
