# Generated by Django 2.1.5 on 2020-07-13 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_auto_20200712_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='question.Question')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('contents', models.TextField()),
                ('submission', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='question.Submission')),
            ],
        ),
    ]
