# Generated by Django 2.1.5 on 2020-07-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_submission_submissionfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='slug',
            field=models.SlugField(default=None),
        ),
    ]
