# Generated by Django 2.1.5 on 2020-08-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0008_question_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
