# Generated by Django 2.1.5 on 2020-08-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0010_auto_20200810_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='solved',
            field=models.BooleanField(default=False),
        ),
    ]
