# Generated by Django 2.1.5 on 2020-08-16 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0015_auto_20200816_1657'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('name', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('name', 'lesson')},
        ),
    ]
