# Generated by Django 2.1.5 on 2020-08-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0017_auto_20200816_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(default=None),
        ),
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='question',
            name='slug',
            field=models.SlugField(default=None),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('slug', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('slug', 'lesson')},
        ),
    ]
