# Generated by Django 2.1.5 on 2020-08-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0021_auto_20200819_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='position',
            field=models.IntegerField(default=1),
        ),
    ]
