# Generated by Django 2.1.5 on 2020-08-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0022_question_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='position',
            field=models.IntegerField(default=1),
        ),
    ]
